### ISSUE TITLE
API.roblox.com is deprecated

### ISSUE THREAD

**Issue by mwalden2004** [matthewdean/roblox-web-apis#31]
https://devforum.roblox.com/t/action-needed-sunsetting-apirobloxcom/1796897

Roblox will be removing the api.roblox.com endpoint, and this should be reflected in these docs.

**Comment by JJ-gren** [comment]
e

**Comment by VSCPlays** [comment]
Roblox recently sunsetted that api

**Comment by robloxianstudio123** [comment]
my fork contains that but i removed it [completely from the README.md](https://github.com/robloxianstudio123/roblox-web-apis/blob/master/README.md)
