### ISSUE TITLE
I'm getting "404 error" trying to get a player status

### ISSUE THREAD

**Issue by NeuberNG** [matthewdean/roblox-web-apis#38]
Hello, I'm kind a new in programming but I have a few skills. I'm using Node-Red to get json data from my Friend's list but started from today getting a "404". 
The payload message returns: ﻿{"errors":[{"code":404,"message":"NotFound"}]}
I try this URL: https://api.roblox.com/users/297881262/onlinestatus/

**Comment by Aidgods** [comment]
you need a cookie

**Comment by matthewdean** [comment]
api.roblox.com has been removed so we've removed this endpoint from the list
