### ISSUE TITLE
setup.roblox.com is not possible to use

### ISSUE THREAD

**Issue by Accoast** [matthewdean/roblox-web-apis#39]
When I try to open any link on [setup.roblox.com](http://setup.roblox.com/) in chrome i get `NET::ERR_CERT_COMMON_NAME_INVALID` error.
![image](https://user-images.githubusercontent.com/119062384/221840519-d68cabef-1eeb-4bf2-bf87-41165f55c199.png)

**Comment by raymonable** [comment]
try setup.rbxcdn.com

**Comment by matthewdean** [comment]
All links in the README have been updated to point to setup.rbxcdn.com
