### ISSUE TITLE
premium api

### ISSUE THREAD

**Issue by the7fr** [matthewdean/roblox-web-apis#46]
i’m trying to get whether a user has premium, the api https://premiumfeatures.roblox.com/v1/users/1/validate-membership is outdated and it will just say “unauthorized”

**Comment by ManHatos** [comment]
that endpoint does seem to work but requires a session cookie

**Comment by the7fr** [comment]
> that endpoint does seem to work but requires a session cookie

i found a way by using the rolimons api along with the “premium” part

**Comment by Paficent** [comment]
Close this issue, not relevant to the repository
