### ISSUE TITLE
Roblox deleted the api doc files

### ISSUE THREAD

**Issue by caelmn** [matthewdean/roblox-web-apis#49]
Roblox deleted these files?? DId they try hiding the api from the public?? Or did they move the link?

**Comment by BizzarBlitz** [comment]
Saw this on the [devforum](https://devforum.roblox.com/t/swagger-docs-are-no-longer-available-on-most-but-not-all-subdomains/3187954), you just need to put an extra `/` character before `docs` in the url to fix it (e.g. [badges.roblox.com/docs](https://badges.roblox.com/docs) becomes [badges.roblox.com//docs](https://badges.roblox.com//docs))

**Comment by matthewdean** [comment]
Thanks for flagging this and sharing the workaround. I'm going to assume Roblox will treat this as a bug and fix it - otherwise can update all the URLs.

**Comment by BizzarBlitz** [comment]
Update: Turns out they [moved the docs to the creator docs website](https://devforum.roblox.com/t/swagger-docs-are-no-longer-available-on-most-but-not-all-subdomains/3187954/13)
Seems like you need to update the URLs :/

**Comment by matthewdean** [comment]
Updated the URLs of individual API sites to include the double slash workaround, as it seems Roblox is not willing to restore them at their original URLs. Added a banner at the top pointing people to the creator docs website which offers a unified docs viewer.
