### ISSUE TITLE
Missing the new headshot/bust thumbnails

### ISSUE THREAD

**Issue by DigiTechs** [matthewdean/roblox-web-apis#8]
The APIs can be found here:

http://www.roblox.com/bust-thumbnail/json?userId=2025110&height=180&width=180 for the image generated on profile pages
http://www.roblox.com/headshot-thumbnail/json?userId=1390724&width=420&height=420 for the image generated in PMs

Both of them return JSON responses like the following:

```
{"Url":"http://t2.rbxcdn.com/a6f88a9745d6245714b00db8a6d2705f","Final":true}
```

**Comment by matthewdean** [comment]
Thanks, fixed.
